rss_reader/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('rss_readers.urls', namespace='rss_readers')),
]

rss_readers/urls.py
"""Определяет схемы URL для rss_readers"""

from django.conf.urls import url

from . import views

urlpatterns = [
	#Домашняя страница
	url(r'^$', views.index, name='index'),

	#Вывод всех каналов
	url(r'^feeds/$', views.feeds, name='feeds'),

	#Cтраница с RSS каналом
	url(r'^feeds/(?P<feed_id>\d+)/$', views.feed, name='feed'),

	#Страница для добавления нового RSS канала
	url(r'^new_feed/$', views.new_feed, name='new_feed'),

	#Страница для редактирования RSS канала
	url(r'^edit_feed/(?P<feed_id>\d+)/$', views.edit_feed, name='edit_feed'),

	
]

users/urls.py
"""Определяет схемы URL для пользователей"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns= [
	#Страница входа
	url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),

	#Страница выхода
	url(r'^logout/$', views.logout_view, name='logout'),

	#Страница регистрации
	url(r'^register/$', views.register, name='register'),

]

rss_readers/models.py
from django.db import models
from django.contrib.auth.models import User

class Feed(models.Model):
	"""RRS канал, который добавляет пользователь"""
	title = models.CharField(max_length=200)
	link = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	category = models.CharField(max_length=200)
	owner = models.ForeignKey(User)

	def __str__(self):
		"""Возвращает строковое представление модели"""
		return self.title

users/models.py
from django.db import models

# Create your models here.

rss_readers/forms.py
from django import forms

from .models import Feed

class FeedForm(forms.ModelForm):
	class Meta:
		model = Feed
		fields = ['title', 'link', 'category']
		labels = {'title': 'Title', 'link': 'RSS feed', 'category': 'Category'}

rss_readers/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth import logout

from django.contrib.auth.decorators import login_required

from .models import Feed
from .forms import FeedForm

from bs4 import BeautifulSoup
import re
import requests

def index(request):
	"""Домашняя страница приложения RSS reader"""
	return render(request, 'rss_readers/index.html')

@login_required
def feeds(request):
	"""Выводит список RSS каналов"""
	feeds = Feed.objects.filter(owner=request.user).order_by('date_added')
	context = {'feeds': feeds}
	return render(request, 'rss_readers/feeds.html', context)


class HTML_Items():
	def __init__(self, title, description, href):
		self.title = title
		self.description = description
		self.href = href
		
@login_required
def feed(request, feed_id):
	"""Выводит RSS канал"""
	feed = Feed.objects.get(id=feed_id)
	#Проверка того, что канал принадлежит текущему пользователю
	if feed.owner != request.user:
		raise Http404
	xml = requests.get(feed.link)
	soup = BeautifulSoup(xml.content, 'xml')
	#print(soup.original_encoding)
	#soup = BeautifulSoup(xml.content.decode(soup.original_encoding), 'xml')
	#print(xml.content.decode(soup.original_encoding))

	items_title = [item.title.string for item in soup.find_all('item')]
	items_description = [item.description.string for item in soup.find_all('item')]
	items_link = [item.link.string for item in soup.find_all('item')]

	items_description = list(map(lambda it: re.sub(r'<[^>]*>', '', it), items_description))

	context = {'feed': feed, 'items': [HTML_Items(items_title[i], items_description[i], items_link[i]) for i in range(len(items_description))]}
	return render(request, 'rss_readers/feed.html', context)

@login_required
def new_feed(request):
	"""Определяет новый RSS канал"""
	if request.method != 'POST':
		#Данные не отправились; создаётся новая форма
		form = FeedForm()
	else:
		#Отправлены данные POST; обработать данные
		form = FeedForm(data=request.POST)
		if form.is_valid():
			new_feed = form.save(commit=False)
			new_feed.owner = request.user
			new_feed.save()
			return HttpResponseRedirect(reverse('rss_readers:feeds'))

	context = {'form': form}
	return render(request, 'rss_readers/new_feed.html', context)

@login_required
def edit_feed(request, feed_id):
	"""Редактирует существющий RSS канал"""
	feed = Feed.objects.get(id=feed_id)
	if feed.owner != request.user:
		raise Http404

	if request.method != 'POST':
		#Исходный запрос; форма заполняется данными текущего канала
		form = FeedForm(instance=feed)
	else:
		#Отправка данный POST; обработать данные
		form = FeedForm(instance=feed, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('rss_readers:feed', args=[feed.id]))

	context = {'feed':feed, 'form': form}
	return render(request, 'rss_readers/edit_feed.html', context)

users/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
	"""Завершает сеанс работы с приложением"""
	logout(request)
	return HttpResponseRedirect(reverse('rss_readers:index'))

def register(request):
	"""Pегистрирует нового пользователя"""
	if request.method != 'POST':
		#Отобразить пустую форму регистрации
		form = UserCreationForm()
	else:
		#Обработка заполненной формы
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			#Выполнение входа и перенапраление на домашнюю страницу
			authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
			login(request, authenticated_user)
			return HttpResponseRedirect(reverse('rss_readers:index'))
	context = {'form': form}
	return render(request, 'users/register.html', context)

rss_readers/templates/rss_readers/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>RSS reader</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

    <body>
      <nav class="navbar navbar-default" style="background-color: #e6e6fa; ">
        <div class="container">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar"
		aria-expanded="false" aria-controls="navbar">
	    </button>
	    <a class="navbar-brand" href="{% url 'rss_readers:index' %}">
		RSS reader</a>
	  </div>

	  <div id="navbar" class="navbar-collapse collapse">
	    <ul class="nav navbar-nav">
	      <li><a href="{% url 'rss_readers:feeds' %}">Feeds</a></li>
	    </ul>

	  <div id="navbar" class="navbar-collapse collapse">
	    <ul class="nav navbar-nav">
	      <li><a href="{% url 'rss_readers:new_feed' %}">Add a new feed</a></li>
	    </ul>

	    <ul class="nav navbar-nav navbar-right">
	      {% if user.is_authenticated %}
		<li><a>Hello, {{user.username }}!</a></li>
		<li><a href="{% url 'users:logout' %}">Log out</a></li>
	      {% else %}
		<li><a href="{% url 'users:register' %}">Register</a></li>
		<li><a href="{% url 'users:login' %}">Log in</a></li>
	      {% endif %}
	    </ul>
	  </div><!--/.nav-collapse -->

	</div>
      </nav>

	  <div class="container">
	    <div class="page-header">
	      {% block header %}{% endblock header %}
	    </div>
	    <div>
              {% block content %}{% endblock content %}
	    </div>

	  </div> <!-- /container -->

    </body>
</html>

rss_readers/templates/rss_readers/edit_feed.html
{% extends "rss_readers/base.html" %}

{% load bootstrap3 %}

{% block header %}
  <h2>Edit feed:</h2>
{% endblock header %}

{% block content %} 

  <form action="{% url 'rss_readers:edit_feed' feed.id %}" method='post'>
    
{% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Save changes</button>
    {% endbuttons %}
  </form>

{% endblock content %}

rss_readers/templates/rss_readers/feed.html
{% extends 'rss_readers/base.html' %}

{% block header %}
	<h2>{{ feed }}</h2>
	<p><a href="{% url 'rss_readers:edit_feed' feed.id %}">(edit feed)</a></p>
{% endblock header %}

{% block content %}

<ul>
  {% for i in items %}
      <li>
        <h4><a href="{{ i.href }}" style="color: #415b76; !important"><b>{{ i.title }}</b></a></h4>
        <i>{{ i.description }}</i>
      </li>
  {% endfor %}
</ul>

{% endblock content %}

rss_readers/templates/rss_readers/feeds.html
{% extends 'rss_readers/base.html' %}

{% block header %}
  <h2>Feeds</h2>
{% endblock header %}

{% block content %}

{% for feed in feeds %}
  <div style="background: #c4e2f2; !important" class="panel panel-info">
    <div class="panel-body">
      <a href="{% url 'rss_readers:feed' feed.id %}" style="color: #415b76; !important"><b>{{ feed }}</b></a>
      <small>
        <a href="{% url 'rss_readers:edit_feed' feed.id %}">(edit feed)</a>
      </small>
      <span style="background: #415b76; !important" class="badge pull-right">{{ feed.category }}</span>
    </div> 
  </div>
{% empty %}
  <li>No tasks have been added yet</li>
{% endfor %} 


{% endblock content %}

rss_readers/templates/rss_readers/index.html
{% extends 'rss_readers/base.html' %}

{% block header %}
  <div style="background: #e6e6fa; !important"  class='jumbotron'>
    <h2>Learn about the news quickly.</h2>
    <h3>RSS reader helps you to read RSS feeds and save your favorite RSS feeds.</h3>
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to add RSS feeds.
  </h2>
  <h2>
    If you already have your RSS feed list, <a href="{% url 'users:login' %}">log in</a> to <a href="{% url 'rss_readers:feeds' %}">view</a> or change it.
  </h2>

{% endblock content %}

rss_readers/templates/rss_readers/new_feed.html
{% extends "rss_readers/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new feed:</h2>
{% endblock header %}

{% block content %} 

  <form action="{% url 'rss_readers:new_feed' %}" method='post'
      class="form">

{% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Add feed</button>
    {% endbuttons %}

  </form>

{% endblock content %} 

users/templates/users/login.html
{% extends "rss_readers/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Log in</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'rss_readers:index' %}" />
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends "rss_readers/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Register.</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">Register</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'rss_readers:feeds' %}" />
  </form>

{% endblock content %}